### ISSUE TITLE
Q-Chem hessian should be reported using ASE units

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1120]
### What is the issue?

Currently, the Q-Chem calculator results presents the Hessian in internal Q-Chem units. However, if it's a first-class result, it really should be in ASE units.

https://github.com/Quantum-Accelerators/quacc/blob/d2006932233333a3ee55e5850dfd5e71fea09855/src/quacc/calculators/qchem/io.py#L178-L181

This is where the Hessian is parsed. If someone wants to address this issue, what they need to do is:

1. Find out the units of the Hessian from Q-Chem's documentation
2. Use the ASE `units` module to convert the Hessian to ASE's accepted units
3. Write a test for the new behavior

CC @samblau.

**Comment by SarojArchana** [comment]
@Andrew-S-Rosen Hello, I am interested in addressing this issue. Could you please assist me by providing information on where I can find Q-Chem's documentation and also assign this issue to me.

**Comment by samblau** [comment]
@SarojArchana  - the Q-Chem Hessian is being parsed directly from the relevant temporary scratch file. I do not believe there is any associated documentation in the Q-Chem manual, as typically only developers interact with the scratch files. You can assume that the Hessian is in "atomic units", although I don't know of the top of my head what the atomic units of a Hessian would be.

**Comment by Rahul-Verma97** [comment]
@samblau What is the conversion factor to convert to convert results["hessian"]  from Q-cem units to ASE units?

**Comment by SarojArchana** [comment]
@samblau What is the conversion factor to convert to convert results["hessian"] from Q-cem units to ASE units?

**Comment by Andrew-S-Rosen** [comment]
@SarojArchana: As noted in the original issue report and by Sam, part of resolving this issue is to find out what the correct conversion factor is. If we knew what it was offhand, we'd have fixed it ourselves.

Also, I don't assign issues. Feel free to open a PR if you figure it out.

**Comment by Andrew-S-Rosen** [comment]
@samblau, @SarojArchana: the unit of the Hessian in Q-Chem are Hartree/bohr^2/amu.

**Comment by Andrew-S-Rosen** [comment]
This issue has now been closed.
