### ISSUE TITLE
Espresso phonon tests failing on `main`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1504]
### Details about the quacc environment

- **quacc version**: `main`
- **Python version**: 3.9+

### What is the issue?

See https://github.com/Quantum-Accelerators/quacc/actions/runs/7479489827/job/20356794813#step:7:175. FYI: @tomdemeyere. Likely a result of the ASE MR.

### How can we easily reproduce the issue?

```python
# Paste your *minimal* example code here
```

**Comment by tomdemeyere** [comment]
This should be fixed by #1404 I can open a quick MR before that if needed

**Comment by Andrew-S-Rosen** [comment]
Good to know! Ultimately, I'll leave it up to you. Time-permitting, a separate PR would be helpful, unless you think #1404 will be finished in the next day or so.
