### ISSUE TITLE
Add some general, ASE-based MD compute jobs

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1577]
### What new feature would you like to see?

It would be nice to add in some MD workflows, ideally in [`quacc/recipes/common`](https://github.com/Quantum-Accelerators/quacc/tree/main/src/quacc/recipes) so the various codes could call it. This would be based around ASE. It isn't difficult to do, but I'm not an MD expert so don't know the ideal defaults and such to pick.

**Comment by tomdemeyere** [comment]
FYI: I have that on my pile of things to-do, when I have time

**Comment by Andrew-S-Rosen** [comment]
Cool! I'm not an MD expert so hesitated to make any formal decisions regarding defaults/best practices. 

For what it's worth, here is an example from @alinelena I was thinking about loosely adapting (but then ran out of time to pursue for now): https://gitlab.com/drFaustroll/lavello/-/blob/main/md.py?ref_type=heads.

**Comment by alinelena** [comment]
@tomdemeyere you can adapt the md.py at the moment it is just a stream of consciousness and vast majority is reading the input params. @ElliottKasoar in my team is looking into something similar so we may consider having a one approach.

**Comment by tomdemeyere** [comment]
@alinelena 

I had a very quick look, If I understand correctly this is opt + remove rot + boltzmann + md ?

**Comment by alinelena** [comment]
yes... in theory all the steps like removing com and boltzman shall be optional.

**Comment by Andrew-S-Rosen** [comment]
Note to self: Some nice work is done here too https://github.com/materialsvirtuallab/matgl/blob/da3dab9affa09feb391351ab2e9fa38862f2c31d/src/matgl/ext/ase.py#L362
