### ISSUE TITLE
Using environment variables, there is no easy way to set a setting as `None`

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#1688]
### What would you like to report?

I use parsl but I often want to do quick tests without workflow engines.

For this I would like to be able to do something like export QUACC_WORKFLOW_ENGINE = "local" or QUACC_WORKFLOW_ENGINE =

But this gets shutdown by an error. "  Input should be 'covalent', 'dask', 'parsl', 'prefect', 'redun' or 'jobflow' [type=literal_error, input_value='', input_type=str]"

Currently I have no way to run them locally, since I have parsl installed, quacc will by default set the workflow engine setting to parsl.

**Comment by Andrew-S-Rosen** [comment]
Thanks for the report and apologies for not communicating this effectively. The "local" option has been removed a little while back and replaced with `None` as an option. The canonical way to do this is to do:

```yaml
WORKFLOW_ENGINE:
```

or

```yaml
WORKFLOW_ENGINE: null
```

in your `~/.quacc.yaml`, both of which are YAML syntax for the Python `None`. There is a small comment about it [here](https://quantum-accelerators.github.io/quacc/user/settings/settings.html#using-a-yaml-file).

Alternatively, from the command line you can do 

```bash
quacc set WORKFLOW_ENGNE None # or null
```
which will automatically get transformed to the proper `Null` in YAML.

**Comment by tomdemeyere** [comment]
Thanks!

export QUACC_WORKFLOW_ENGINE=null does not work for me?

**Comment by Andrew-S-Rosen** [comment]
Just was editing my comment. I haven't tried doing this via the environment variables. I'll look into how that's getting handled. My guess is that the environment variable is being handled as a string only and not getting transformed. You'd expect `export QUACC_WORKFLOW_ENGINE=` to work.

**Comment by tomdemeyere** [comment]
@Andrew-S-Rosen 

```
  Input should be 'covalent', 'dask', 'parsl', 'prefect', 'redun' or 'jobflow' [type=literal_error, input_value='', input_type=str]
```

empty string

**Comment by tomdemeyere** [comment]
Thanks!
