### ISSUE TITLE
MontyStore does not seem to be concurrent friendly

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#1728]
### What would you like to report?

When using MontyStore, if two or more jobs happen to finish around the same time, you will get:

```python
...
  File "/work/e89/e89/td5g20/.mambaforge/envs/workflows/lib/python3.11/site-packages/montydb/storage/sqlite.py", line 135, in create_table
    with self._connect(db_file) as conn:
    ^^^^^^^^^^^^^^^^^
  File "/work/e89/e89/td5g20/.mambaforge/envs/workflows/lib/python3.11/site-packages/montydb/storage/sqlite.py", line 126, in _connect
    self.__conn.executescript(self.db_pragmas + ";" + wcon_pragmas)
    ^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked
```

Is there any way to avoid this?

**Comment by Andrew-S-Rosen** [comment]
Thanks for asking. See the related issue report in the maggma repo: https://github.com/materialsproject/maggma/issues/832. In short, there is a fair bit more that should be done to properly handle file-based stores in a high-throughput setting. I encourage you to open an issue there to highlight this further.

**Comment by Andrew-S-Rosen** [comment]
Also see https://github.com/davidlatwe/montydb/discussions/84 in the montydb repo.

**Comment by Andrew-S-Rosen** [comment]
That seems like it could be wise.
