### ISSUE TITLE
Store "corrected" entries for VASP MP runs 

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1747]
### What new feature would you like to see?

The VASP MP runs store the emmet task doc, which is based on the raw data. However, to make it 1:1 compatible with MP, one generally has to apply post-hoc corrections based on +U and anions. Rather than relying on the user to wade through this with the Pymatgen compatability classes, we should simply store that info in the output schema.

**Comment by zulissimeta** [comment]
It would also be great if these generated MP formation energies using the standard reference energies!
