### ISSUE TITLE
Ensure Espresso recipes work without calls to `os.chdir`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1807]
### Details about the quacc environment

- **quacc version**: 0.6.8
- **Python version**: 3.9+

### What is the issue?

In my ongoing attempt to make `quacc` safe for multithreading by removing `os.chdir` calls, it appears that Espresso is one of the remaining sets of recipes that are not compatible. 

### How can we easily reproduce the issue?

See [here](https://github.com/Quantum-Accelerators/quacc/actions/runs/8107193856/job/22158308799?pr=1600).

**Comment by Andrew-S-Rosen** [comment]
Reopening this issue because it's not fully solved just yet. See [here](https://github.com/Quantum-Accelerators/quacc/actions/runs/8131380762/job/22220641362?pr=1600). Will update with more details.

**Comment by tomdemeyere** [comment]
> Reopening this issue because it's not fully solved just yet. See [here](https://github.com/Quantum-Accelerators/quacc/actions/runs/8131380762/job/22220641362?pr=1600). Will update with more details. 
> 
> 
> 
> Edit: Seems like the issue is with `tests/dask/test_espresso_recipes.py::test_phonon_grid_qplot`.
> 
> 
> 
> The `CRASH` files indicate:
> 
> 
> 
> ```
> 
> 
> 
>  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
>      task #         0
> 
>      from seqopn : error #        99
> 
>      error opening ./_ph0/pwscf.q_1/pwscf.recover
> 
>  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
> ```
> 
> 
> 
> Files: 
> 
> [test_run.zip](https://github.com/Quantum-Accelerators/quacc/files/14473740/test_run.zip)
> 
> 
> 
> @tomdemeyere: if you have any ideas, I'm all ears! 
> 
> 

Ah, weird, do you have an idea why this was not showing up in the test of my previous PR? (knowing this might help me deal with it)
