### ISSUE TITLE
Latest and greatest quacc version requires unreleased version of ASE

### ISSUE THREAD

**Issue by lbluque** [Quantum-Accelerators/quacc#1937]
### What would you like to report?

Looks like the latest quacc version [requires ASE > 3.22.1](https://github.com/Quantum-Accelerators/quacc/blob/cb85bc51dc3590e3c3847406dcae02c156ac981e/pyproject.toml#L30) which is not available on pypi yet.

Just noting it because this breaks the pip install for the latest quacc.

btw quacc is awesome :)

**Comment by Andrew-S-Rosen** [comment]
Hi @lbluque! Thanks for reaching out! Yes, this is indeed true (as [alluded to](https://quantum-accelerators.github.io/quacc/install/install.html#installing-quacc) in the installation docs).

Unfortunately, ASE has not had a release in multiple years and despite my best efforts, I have not been able to get the lead dev to mint a new release. As an ASE co-maintainer myself, this has been a bit of a political struggle, but I have largely given up hope. 😅

I ended up pinning ASE to > 3.22.1 to make sure quacc runs correctly. The alternative is to not put a lower bound in `pyproject.toml` and raise an error in the `__init__.py` if an old version of ASE is detected, but in either case, there's not much of a solution aside from forcing the user to install the dev version of ASE.

Open to suggestions on how to improve the user experience if you have them!

**Comment by lbluque** [comment]
Ah, thanks for the quick explanation! Not a big deal for me to run the latest ASE anyway --- hopefully lead devs come around to making releases more often

**Comment by Andrew-S-Rosen** [comment]
I will cry tears of joys when/if the day ever comes! 😅 I've been told "just one more week" for over a year now...
