### ISSUE TITLE
Add more MLPs: ALIGN-FF, NequIP, GAP, DP, and FLARE

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1940]
### What new feature would you like to see?

We already have support for MACE-MP-0, CHGNet, and M3GNet in `quacc.recipes.mlp`. We should also add support for:
- [ALIGN-FF](https://github.com/usnistgov/alignn/tree/main/alignn/ff#L220)
- [NequIP](https://github.com/mir-group/nequip/blob/9882562b32b89785e56c9e7681f0d3527d900568/nequip/ase/nequip_calculator.py#L19)
- [GAP](https://github.com/libAtoms/QUIP/blob/public/quippy/quippy/potential.py#L43)
- [DP](https://github.com/deepmodeling/deepmd-kit/blob/b875ea8f6661b6e1567537ead7e2b4a8b14ea113/deepmd/calculator.py#L34)
- [FLARE](https://github.com/mir-group/flare/blob/700f2c86376a5f439483b55b7b0b2129fd0ca48e/flare/bffs/gp/calculator.py#L46)

**Comment by Nekkrad** [comment]
@Andrew-S-Rosen  might be working on this in the near future (when time allows).  Would you prefer expanding the pick_calculator function or creating calculators for each MLP? I reckon the first approach is probably the safest.

**Comment by Andrew-S-Rosen** [comment]
I'd go with the former. The only time we should create a custom calculator is if the original calculator does not have all the features we need, which is rare (right now, only VASP, Espresso, and Q-Chem require this). Expanding on the picker function seems like the easiest approach to me. 

It would also involve updating the `tests/requirements-mlp.txt` file:
https://github.com/Quantum-Accelerators/quacc/blob/main/tests/requirements-mlp.txt

as well as the `pyproject.toml` file:
https://github.com/Quantum-Accelerators/quacc/blob/3ab1630603fdff718a8d16080096be083b1560f7/pyproject.toml#L49

but otherwise shouldn't be too painful.

**Comment by jackpm14** [comment]
@Andrew-S-Rosen Might see if I can get some work in. For ALIGNN-FF, would the 'default' path be best, or would you prefer to have it added as ALIGNN-FF-Default?

**Comment by Andrew-S-Rosen** [comment]
@jackpm14: I'm a bit undecided. It [seems](https://github.com/usnistgov/alignn/blob/main/alignn%2Fff%2Fff.py#L73) there are several distinct ALIGN-FF models but I think if a user requested ALIGN-FF as the method they should get whatever is the current standard.

Enumerating each individual model seems like a code maintenance disaster, but having just "alignff" as the method means it may make versioning less obvious as you saw with MACE-MP-0.

For now, I'd suggest just supporting "alignff" to be whatever the state of the art is at this point in time. That said, I'm very much open to suggestions here.
