### ISSUE TITLE
Support Prefect 3

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#2221]
### Details about the quacc environment

- **quacc version**: 0.9.2
- **Python version**: 3.10.14
- **prefect version**: 3.0.0.rc2

### What is the issue?

When using Prefect 3.x, most dynamic workflows in quacc become broken.

### How can we easily reproduce the issue?

```
pip install quacc[dev]
pip install prefect==3.0.0rc2
quacc set WORKFLOW_ENGINE prefect
```

```python
from quacc import flow, job, subflow


@job
def add(a, b):
    return a + b

@job
def make_more(val):
    return [val] * 3

@subflow
def add_distributed(vals, c):
    return [add(val, c) for val in vals]

@flow
def dynamic_workflow(a, b, c):
    result1 = add(a, b)
    result2 = make_more(result1)
    return add_distributed(result2, c)

assert [r.result() for r in dynamic_workflow(1, 2, 3)] == [6, 6, 6]
```

Alternatively, you can run `pytest tests/prefect/test_syntax.py` to find more examples.

In running the above minimal example, you'll find that it stalls completely (if run via `pytest`) or simply returns an infinite loop of errors (if run in an IPython console or REPL).

### Any Ideas Why?

The root cause is the following monkeypatch:

https://github.com/Quantum-Accelerators/quacc/blob/797602a16a3685741a8db767f19e150a17360d39/src/quacc/__init__.py#L47-L60

If we comment out `PrefectFuture.__getitem__ = _patched_getitem`, the minimal example will run to completion, albeit at the expense of other tests failing since we have removed the implicit deferral of `__getitem__` calls.

I believe the problem is likely related to the fact that there are actually several [new Perfect future classes](https://github.com/PrefectHQ/prefect/blob/578665ed8677ba035e636f6398434047299bbf2d/src/prefect/futures.py) like a `PrefectConcurrentFuture` among others. However, I tried playing around with them and wasn't able to make much progress from a quick effort.

Tagging @zulissimeta as a head's up (and in case you're feeling adventurous...).

**Comment by Andrew-S-Rosen** [comment]
The entire test suite runs to completion if the following small change is made: changing `@job` to `@task` in the line below.

https://github.com/Quantum-Accelerators/quacc/blob/56a923af49ca3c4f0ae3e20672de41c3e383c9ff/src/quacc/__init__.py#L49

In other words, it works perfectly fine if we don't `.submit()` the `__getitem__` call to the concurrent task runner, which the `@job` decorator does automatically. However, it's likely this is not a mergeable change because if we use `@task` here, then the `__getitem__` call will run on server-side in a serial fashion. This has two drawbacks: 1) the server needs the same dependencies as the remote machine; 2) If there are many `__getitem__` calls being made, there may be a bottleneck.

**Comment by zulissimeta** [comment]
This might be related (and if so, it might be worth trying the tests again with the latest prefect3): https://github.com/PrefectHQ/prefect/issues/14036

**Comment by Andrew-S-Rosen** [comment]
Note to self: this does not seem related to https://github.com/PrefectHQ/prefect/issues/14036 since the errors persist in 3.0.0rc15.

**Comment by Andrew-S-Rosen** [comment]
It seems the following is the patch that reproduces the pre-existing behavior in Prefect 2:

```python
# Monkeypatching for Prefect
if _settings.WORKFLOW_ENGINE == "prefect":
    from prefect.client.schemas import State
    from prefect.futures import PrefectFuture

    def _patched_getitem(self, index):
        @job
        def _getitem(future, index_):
            return future[index_]

        future = _getitem(self, index)
        future.wait()
        return future.state

    PrefectFuture.__getitem__ = _patched_getitem
    State.__getitem__ = _patched_getitem
```

It is related to the fact that:
> The PrefectFuture methods are also always synchronous in Prefect 3. Names and return values changed to reflect this:

> PrefectFuture.get_state() is now PrefectFuture.state
> PrefectFuture.wait() now returns None instead of a State
> Wait for the future to complete, then retrieve the state separately:

as noted in [the prefect 3 docs](https://docs-3.prefect.io/3.0rc/resources/upgrade-prefect-3#breaking-changes-errors-and-resolutions).

**Comment by Andrew-S-Rosen** [comment]
Prefect 3 support will be fixed with the upstream Prefect PR I opened: https://github.com/PrefectHQ/prefect/pull/14900.
