### ISSUE TITLE
Every zpath call needs a str() in case it's a pathlib.Path

### ISSUE THREAD

**Issue by zulissimeta** [Quantum-Accelerators/quacc#2335]
### Details about the quacc environment

- **quacc version**: latest
- **Python version**: 3.11
- **Monty version**: 2024.7.12

### What is the issue?

monty.os.path.zpath uses str.removesuffix, which doesn't work for Path objects. 2/4 zpath calls in quacc use str() to keep this safe, but two are missing them. 

Something about monty-2024.7.12 causes this change.

### How can we easily reproduce the issue?

With monty-2024.7.12:
```
from quacc.runners.prep import calc_cleanup, calc_setup
from monty.os.path import zpath

job_results_dir, _ = calc_setup(None)
zpath(job_results_dir / 'test.gz')
```

**Comment by Andrew-S-Rosen** [comment]
Thank you, @zulissimeta! Looks like it was due to https://github.com/materialsvirtuallab/monty/pull/682. You beat dependabot to this one: https://github.com/Quantum-Accelerators/quacc/pull/2339.

Should be patched now.
