### ISSUE TITLE
parsl_resource_specification does not work correctly with espresso

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#2411]
### Details about the quacc environment

- **quacc version**: master
- **Python version**: 3.11.8

### What is the issue?

I tried to run espresso calculations with the `parsl_resource_specifications`, but they ended up running in serial.  In `settings.validate_espresso_parallel_cmd` printing `parsl_mpi_prefix` results in `None`. Printing os.environ["PARSL_MPI_PREFIX"] in `calculators.espresso.__init__` works correctly. This suggests that `settings.validate_espresso_parallel_cmd` gets called before and can't update the command correctly?

### How can we easily reproduce the issue?

``` python
resource_specification = {
    "num_nodes": 1,
    "ranks_per_node": 128,
    "num_ranks": 128,
    "launcher_options": "-vv --cpu-freq=2250000 --hint=nomultithread --distribution=block:block",
}

relax_job_parsl = redecorate(relax_job, job(parsl_resource_specification=resource_specification))
@subflow
def relax_atoms_list(atoms_list):
    results = []

    for atoms in atoms_list:
        results.append(relax_job_parsl(atoms, kspacing=0.025, input_data=input_data))

    return results


atoms_list = [bulk("Pt")] * 16
futures = relax_atoms_list(atoms_list)
```

**Comment by Andrew-S-Rosen** [comment]
This behavior has never been tested to the best of my knowledge, so I would not be surprised that it is not fully functional yet.

**Comment by Andrew-S-Rosen** [comment]
Thanks for the update! I don't see anything wrong with it. Is there a downside? 😅

**Comment by tomdemeyere** [comment]
> Thanks for the update! I don't see anything wrong with it. Is there a downside?

It is not immediately clear to me, I think after discussion it was decided that putting it in `settings.py` was better, but it does not seem to work as of now.

Let me open a meta-issue on Parsl, I think it might be clearer and this one can be closed.
