### ISSUE TITLE
Error thrown from example script: AttributeError: 'function' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by wladerer** [Quantum-Accelerators/quacc#2492]
### Details about the quacc environment

- **quacc version**: 0.9.3
- **Python version**: 3.11

Also: 

covalent                  0.235.1rc0
covalent-cloud            0.65.1

### What is the issue?

I am unsure if I installed something incorrectly or this is more of an issue with Covalent, but I will start here. 

Something seems like its being passed to covalent without being initialized the way it wants. 

```python
  File "/p/work1/wladerer/wp2/jobby.py", line 23, in <module>
    dispatch_id = ct.dispatch(workflow)(1, 2, 3)  
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/p/home/wladerer/.pyenv/versions/3.11.7/lib/python3.11/site-packages/covalent/_dispatcher_plugins/local.py", line 135, in dispatch
    if "triggers" in orig_lattice.metadata:
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'metadata'
```
Thanks!

### How can we easily reproduce the issue?

```python
import covalent as ct
from quacc import flow, job


@job  


def add(a, b):
    return a + b


@job
def mult(a, b):
    return a * b


@flow  
def workflow(a, b, c):
    output1 = add(a, b)
    output2 = mult(output1, c)
    return output2


dispatch_id = ct.dispatch(workflow)(1, 2, 3)  


result = ct.get_result(dispatch_id, wait=True)  


print(result)  # 9
```

**Comment by Andrew-S-Rosen** [comment]
@wladerer what happens if you replace `@job` with `@ct.electron` and `@flow` with `@ct.lattice`. Then your question becomes a covalent one directly.

**Comment by wladerer** [comment]
Changing to

```python
import covalent as ct
from quacc import flow, job


@ct.electron
def add(a, b):
    return a + b


@ct.electron
def mult(a, b):
    return a * b


@ct.lattice
def workflow(a, b, c):
    output1 = add(a, b)
    output2 = mult(output1, c)
    return output2



dispatch_id = ct.dispatch(workflow)(1, 2, 3)
result = ct.get_result(dispatch_id, wait=True)
print(result)  # 9

```
Resulted in the following output

```

Lattice Result
==============
status: COMPLETED
result: 9
input args: 1, 2, 3
input kwargs: 
error: None

start_time: 2024-10-10 22:57:17.338061
end_time: 2024-10-10 22:57:18.603973

results_dir: /p/home/wladerer/.cache/covalent/results/94aaa1b9-45a1-454b-b0eb-1bbe9304b777
dispatch_id: 94aaa1b9-45a1-454b-b0eb-1bbe9304b777

Node Outputs
------------
add(0): 3
:parameter:1(1): 1
:parameter:2(2): 2
mult(3): 9
:parameter:3(4): 3
:postprocess:reconstruct(5): 9
```

**Comment by Andrew-S-Rosen** [comment]
Interesting. Thanks for the report. I am out of town at the moment but will look at this early next week. Admittedly, I'm not 100% sure offhand what the error is. The CI tests seem to be passing.

**Comment by Andrew-S-Rosen** [comment]
@wladerer: it looks like the issue here is you have not done `quacc set WORKFLOW_ENGINE covalent`.

**Comment by wladerer** [comment]
Oh you know what, I just started using the ~/quacc.yaml instead of the environment variables. That is most definitely it. 

Thank you! So sorry for the trouble

**Comment by Andrew-S-Rosen** [comment]
No problem! 

Also, just a note that quacc 0.9.3 is a bit old. You may wish to consider updating if viable for your project.

I'll close this now, but feel free to re-open if needed.
