### ISSUE TITLE
Sella object has no attribute `trajectory` error

### ISSUE THREAD

**Issue by arosen93** [Quantum-Accelerators/quacc#422]
This is a bug report from @kumaranu. Have to figure out if this is with Sella or ASE or what.

```
Traceback (most recent call last):
  File "/global/home/users/kumaranu/Documents/tests/quacc_tests/prod6.py", line 25, in <module>
    add_to_lpad(index, atoms, run=RUN)
  File "/global/home/users/kumaranu/Documents/tests/quacc_tests/prod6.py", line 10, in add_to_lpad
    job1 = ts_job(atoms)
  File "/global/home/users/kumaranu/.conda/envs/quacc/lib/python3.9/site-packages/covalent/_workflow/electron.py", line 754, in wrapper
    return electron_object(*args, **kwargs)
  File "/global/home/users/kumaranu/.conda/envs/quacc/lib/python3.9/site-packages/covalent/_workflow/electron.py", line 375, in __call__
    return self.function(*args, **kwargs)
  File "/global/home/users/kumaranu/.conda/envs/quacc/lib/python3.9/site-packages/monty/dev.py", line 113, in decorated
    return _callable(*args, **kwargs)
  File "/global/home/users/kumaranu/quacc/quacc/recipes/newtonnet/core.py", line 190, in ts_job
    dyn = run_ase_opt(atoms, **opt_flags)
  File "/global/home/users/kumaranu/quacc/quacc/util/calc.py", line 238, in run_ase_opt
    dyn.trajectory.filename = optimizer_kwargs[
AttributeError: 'Sella' object has no attribute 'trajectory'
```

**Comment by arosen93** [comment]
@kumaranu:

I am trying to reproduce your issue and am a bit perplexed at the moment.

Could you try the following and let me know what you get?

```python
from ase.build import bulk
from ase.optimize import BFGS
from sella.optimize import Sella

atoms = bulk("Cu")
dyn1 = BFGS(atoms)
print(hasattr(dyn1, "trajectory"))

dyn2 = Sella(atoms)
print(hasattr(dyn2, "trajectory"))
```

Both of those return `True` for me, indicating that `Sella` does indeed have an attribute `trajectory`. So, I'm curious if you get the same.

**Comment by kumaranu** [comment]
(quacc) [kumaranu@n0003 quacc]$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ase.build import bulk
>>> from ase.optimize import BFGS
>>> from sella.optimize import Sella
>>> atoms = bulk("Cu")
>>> dyn1 = BFGS(atoms)
>>> print(hasattr(dyn1, "trajectory"))
False
>>> dyn2 = Sella(atoms)
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
>>> print(hasattr(dyn2, "trajectory"))
False
>>>

**Comment by arosen93** [comment]
@kumaranu:

Thanks! As I suspected. your environment is not using the right version of ASE. I thought we had tried this, but you're going to need to `pip uninstall ase` and then `pip install git+https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip`. Please do that and try the code snippet again.

**Comment by kumaranu** [comment]
I am getting the following error:
```
(quacc) [kumaranu@n0003 quacc]$ pip install git+https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip
Collecting git+https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip
  Cloning https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip to /tmp/pip-req-build-xudv2dp0
  Running command git clone --quiet https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip /tmp/pip-req-build-xudv2dp0
  fatal: unable to access 'https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip/': The requested URL returned error: 403
  error: subprocess-exited-with-error
  
  × git clone --quiet https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip /tmp/pip-req-build-xudv2dp0 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip /tmp/pip-req-build-xudv2dp0 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by arosen93** [comment]
@kumaranu: My apologies. That was a typo on my part.

`pip uninstall ase` and then `pip install https://gitlab.com/argon214/ase/-/archive/efermi/ase-efermi.zip`

**Comment by kumaranu** [comment]
Thanks, @arosen93. It worked out. Now I am getting both trues as well.
`    >>> from ase.vibrations import Vibrations
    >>> n2 = Atoms('N2', [(0, 0, 0), (0, 0, 1.1)],
    ...            calculator=EMT())
    >>> BFGS(n2).run(fmax=0.01)
    BFGS:   0  16:01:21        0.440339       3.2518
    BFGS:   1  16:01:21        0.271928       0.8211
    BFGS:   2  16:01:21        0.263278       0.1994
    BFGS:   3  16:01:21        0.262777       0.0088
    >>> vib = Vibrations(n2)
`

**Comment by arosen93** [comment]
@kumaranu: Great! Then I believe when you run your Sella calculation again, you will not run into this error anymore. I'm going to close this issue, but please tag me if the issue remains.

**Comment by arosen93** [comment]
Closed, thanks to excellent advice by @ehermes!
