### ISSUE TITLE
General ASE `Calculator` for pretrained ML models

### ISSUE THREAD

**Issue by chiang-yuan** [Quantum-Accelerators/quacc#808]
Both `CHGNet` and `MACE` provide ase calculator class. I think general ase calculators defined externally can be easily incorporated into quacc just by changing the import of the existing `EMT` calculator. 

https://github.com/Quantum-Accelerators/quacc/blob/f4b1bdc6f6ccdc88223d6881be54dc44ba6a591b/src/quacc/recipes/emt/core.py#L10

Would it be of interest here? @arosen93 
Now I am working on a small workflow using pretrained models to calculate density, viscosity, etc. Perhaps will be part of [matcal](https://github.com/materialsvirtuallab/matcalc)

**Comment by arosen93** [comment]
Hi @chiang-yuan! Thanks for reaching out. Indeed, this is of significant interest (in fact, I opened an issue about this in #240 many months ago but just never had a chance to get around it).

You are right --- it should be a fairly trivial addition by simply copying the core EMT or tblite recipes and swapping out the calculator. That is how most of the basic recipes in quacc work 😄

**Comment by chiang-yuan** [comment]
Cool. I will be happy to work on this and give it a spin using quacc. Have you considered how api architecture will look like? For example,

```
from ase.build import bulk
from quacc.recipes.ase.core import relax_job
from mace.calculator import MACECalculator

# Make an Atoms object of a bulk Cu structure
atoms = bulk("Cu")

# Define calculator
calculator = MACECalculator(model_paths=model_file, device='cuda')

# Run a structure relaxation on the Atoms object
result = relax_job(atoms, calculator=calculator)
print(result)
```

**Comment by arosen93** [comment]
@chiang-yuan: Happy to work together on this in whatever capacity you'd be interested in! 

I have not used MACE before so would defer to you on the most user-friendly approach. That said, my personal preference is to probably make a new module altogether for MACE even if it means that most of the code will be duplicated from the EMT recipes. The reason for this is that down the line, it's always possible that we would want to add unique functionality to the MACE recipes and then it might be a bit awkward to fit into the EMT recipes themselves. I generally prefer to have each calculator have its own set of recipes for that reason. It may go against the "don't repeat yourself" rule of programming to some extent, but I think it helps here with readability/usability.

With that being said, my recommended approach would be the following:

1. Make a new folder:`quacc/recipes/mace`

2. In that folder, make a file `core.py` to store the "core" recipes.

3. Copy the `relax_job` from `emt.core` into `quacc.recipes.mace.core`

4. Wrap the `relax_job` with a `monty.dev.requires` decorator (see `quacc.recipes.tblite.core` for an example) so the user is appropriately warned if the necessary dependencies for MACE are not installed.

5. Swap out the EMT calculator for the MACE calculator like you did in your example.

6. Custom default arguments as needed.

7. For things like model paths that you probably aren't changing with every single calculation, it probably makes more sense to have them stored in a [settings file](https://quantum-accelerators.github.io/quacc/user/settings.html), as done in `quacc.recipes.newtonnet.core`. 

That should mostly be it! Happy to chat more over GitHub/Slack/Zoom/in person/whatever if you're interested. I don't think this would take very long to add, to be honest.

**Comment by chiang-yuan** [comment]
I see your point keeping `emt` as simple as possible and surely it will help new users (including me) get used to how `quacc` works. I think `quacc.reciepes.ml` module makes sense to me here and is what I meant. I will start work on it and open a PR once I have the preliminary code module. 😸

**Comment by arosen93** [comment]
I think that sounds great! I agree that there's likely sufficient overlap between the ML calculators to group them together in some way just like you initially proposed. Very much looking forward to it. Thank you for taking a stab at it! 😄 Don't hesitate to reach out.

**Comment by Andrew-S-Rosen** [comment]
CC @samblau.
