### ISSUE TITLE
Error while running test locally

### ISSUE THREAD

**Issue by OmAximani0** [Quantum-Accelerators/quacc#834]
I tried to run test with `pytest` but got these errors:
![image](https://github.com/Quantum-Accelerators/quacc/assets/75031769/e9ce7b18-aead-40a4-a524-ca624f09e6f8)

### Test session details
![image](https://github.com/Quantum-Accelerators/quacc/assets/75031769/17874a9a-c680-4831-ae38-203c11048268)

**Comment by OmAximani0** [comment]
After installing ASE it's working fine :+1: 

### Command I used to install ASE
`pip install --upgrade https://gitlab.com/ase/ase/-/archive/master/ase-master.zip`

**Comment by OmAximani0** [comment]
This issue is resolved by my side. Thank you for help @arosen93 :smile:

**Comment by arosen93** [comment]
Great, thanks! It's a bit tricky because I can't include it in the main `pyproject.toml` requirements since PyPI doesn't allow you to include direct GitHub/GitLab links. But I will include it in the `dev` requirements so it's installed automatically for developers.
