### ISSUE TITLE
Typo in `contributing.md`

### ISSUE THREAD

**Issue by OmAximani0** [Quantum-Accelerators/quacc#853]
## Screenshot
![image](https://github.com/Quantum-Accelerators/quacc/assets/75031769/83d9a387-a0e1-477e-afb6-1107d2242ebd)

## Line to fix
https://github.com/Quantum-Accelerators/quacc/blob/8bcadc76d920878523b9983553fe1761b73f4c37/docs/dev/contributing.md?plain=1#L73

**Comment by arosen93** [comment]
Thank you!
